language: go

go:
  - 1.4

install:
  - go get github.com/PuerkitoBio/goquery
  - go get code.google.com/p/go.net/publicsuffix

before_script:
  - chmod +x ./test

script:
  - ./test

notifications:
  slack: gophercn:at1kT18oZQMeLErRW2TjmIZh
